services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/backend
        env_file: "./backend/.env"
        command: python src/manage.py runserver 0.0.0.0:8000

    frontend:
        build: ./frontend
        ports:
            - "5173:5173"
        volumes:
            - ./frontend:/frontend
        env_file: "./frontend/.env"
        command: yarn dev
