# Generated by Django 5.1.2 on 2024-11-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_transaction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_from_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='bank_from', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_to_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='bank_to', to='bank.bank'),
        ),
    ]
