# Generated by Django 5.1.3 on 2024-11-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_transaction_bank_from_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
