# Generated by Django 5.1.3 on 2024-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_bank_bank_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("entertainment", "Развлечения"),
                    ("food", "Еда"),
                    ("transport", "Транспорт"),
                    ("utilities", "Коммунальные услуги"),
                    ("transfer", "Перевод"),
                    ("salary", "Зарплата"),
                    ("investment", "Инвестиции"),
                ],
                max_length=30,
            ),
        ),
    ]
