# Generated by Django 5.1.2 on 2024-11-20 15:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bank_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('entertainment', 'Развлечения'), ('food', 'Еда'), ('transport', 'Транспорт'), ('utilities', 'Коммунальные услуги'), ('transfer', 'Перевод'), ('salary', 'Зарплата'), ('investment', 'Инвестиции')], max_length=30),
        ),
        migrations.CreateModel(
            name='PeriodicPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('creator', models.CharField()),
                ('period_type', models.CharField(choices=[('days', 'Дни'), ('months', 'Месяцы'), ('years', 'Годы')])),
                ('period', models.IntegerField()),
                ('creation_tyme', models.DateTimeField(default=datetime.datetime.now)),
                ('account_from_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodic_account_from', to='bank.account')),
                ('account_to_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodic_account_to', to='bank.account')),
            ],
        ),
    ]
