# Generated by Django 5.1.3 on 2024-11-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0006_alter_transaction_category_periodicpayment"),
        ("bank", "0007_alter_account_balance"),
    ]

    operations = []
