# Generated by Django 5.1.2 on 2024-11-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
