# Generated by Django 5.1.3 on 2024-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_remove_useraccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='api_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
