# Generated by Django 5.1.2 on 2024-11-20 14:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_bank_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('period_type', models.CharField(max_length=100)),
                ('period', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
            ],
        ),
    ]
