# Generated by Django 5.1.2 on 2024-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_periodicpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicpayment',
            name='creator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
